#!/bin/bash

cp .env.example .env

composer install

php artisan key:generate

touch database/database.sqlite

php artisan migrate
php artisan db:seed

npm install

npm run build

open http://synthetic-playground.test
