#!/bin/bash

composer install

cp .env.example .env

php artisan key:generate

touch database/database.sqlite

php artisan migrate
php artisan db:seed

npm install

npm run build

xdg-open synthetic-playground.test
